name: FriendlyWrt for NanoPi R2S

on:
  push:
    paths:
      - "build-number"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          git config --local user.email "i@shensven.com"
          git config --local user.name "GenSven"
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          df -h

      - name: Get Source Code
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328/
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c  --no-clone-bundle -j2

      - name: Generate Configuration File
        run: |
          rm -f friendlywrt-rk3328/configs/config_rk3328
          cp config_rk3328_shensven friendlywrt-rk3328/configs/config_rk3328

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328/
          ./build.sh nanopi_r2s.mk
          df -h

      - name: Assemble Artifact
        run: |
          rm -rf artifact
          mkdir artifact
          cp friendlywrt-rk3328/out/*.img artifact
          cp friendlywrt-rk3328/configs/config_rk3328 artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt for NanoPi R2S
          path: artifact
